# 1.Create a null vector of size 10 but the fifth value which is 1

In [1]:
import numpy as np

In [2]:
(np.arange(10) == 4) .astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

# 2.Create a vector with values ranging from 10 to 49.

In [3]:
Range=np.arange(10,49)
Range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# 3.Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
a = np.random.randint(0,8,(3,3))
a

array([[0, 2, 2],
       [7, 1, 6],
       [0, 0, 2]])

# 4.Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

# 5.Create a 10x10 array with random values and find the minimum and maximum values

In [6]:
matrix = np.random.random((10,10))
print(matrix)
print("minimun value is",matrix.min())
print("maximum value is",matrix.max())

[[0.33560178 0.89702466 0.07931948 0.10682126 0.24053304 0.29072119
  0.49340205 0.47663031 0.31304626 0.04418747]
 [0.50086156 0.06870076 0.16427688 0.84193369 0.98618741 0.86122802
  0.95352859 0.56392433 0.34409612 0.2469524 ]
 [0.49359059 0.26969866 0.28269634 0.3798139  0.09608425 0.53354848
  0.14649747 0.19392938 0.51648037 0.42895426]
 [0.18994718 0.41057796 0.19125539 0.15349789 0.30310714 0.57596956
  0.63872117 0.10436716 0.02554712 0.30035958]
 [0.6568904  0.55885598 0.61224974 0.28093082 0.97681581 0.61070196
  0.4922011  0.91894838 0.66832027 0.23115068]
 [0.85033636 0.9356268  0.7090211  0.90656622 0.80175099 0.29218834
  0.40624231 0.42867801 0.20244824 0.37873386]
 [0.70549464 0.39138825 0.87759138 0.21567636 0.47621775 0.72720607
  0.2389276  0.42564496 0.02508767 0.43688081]
 [0.26313545 0.21287084 0.97879124 0.74152575 0.07433904 0.87804079
  0.92286854 0.9034167  0.85133643 0.65325827]
 [0.14062631 0.82832225 0.53900664 0.96788607 0.23221081 0.03429837
  0.33916194

# 6.Create a random vector of size 30 and find the mean value.

In [7]:
random_vector =np.random.random(30)
random_vector

array([0.79468328, 0.25072801, 0.06648271, 0.35404489, 0.98943375,
       0.4124299 , 0.49144526, 0.20186876, 0.89907531, 0.33356667,
       0.48559966, 0.51693775, 0.08743793, 0.62795366, 0.7869698 ,
       0.34960081, 0.99835932, 0.11843268, 0.98734754, 0.01769116,
       0.0316477 , 0.03257823, 0.96515719, 0.15409168, 0.66740219,
       0.25153341, 0.07506555, 0.61090083, 0.72897423, 0.51754181])

In [8]:
random_vector.mean()

0.4601660557671647